[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "2WVfb7G4DuvwgkJ9wm5SSDypBLECTfmpL78CwAosE3AD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/snndmaa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
