[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
escrow = "Bpy2YAC8LuB4Nvr1dAhQcQkvgAXt18SyjY5d61WAwePB"

[programs.localnet]
escrow = "Bpy2YAC8LuB4Nvr1dAhQcQkvgAXt18SyjY5d61WAwePB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/snndmaa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
